import type { Lang } from './i18n';

export type Feature = {
  slug: string;
  label: string;
  detail: string;
  eyebrow: string;
  title: string;
  intro: string;
  points: string[];
  sections?: { title: string; text: string }[];
  notice?: { title: string; text: string };
};

export const featureCatalog: Record<Lang, Feature[]> = {
  pt: [
    {
      slug: 'agenda-horarios', label: 'Agenda e horários', detail: 'Organiza o teu dia', eyebrow: 'Agenda', title: 'Tudo o que precisas para gerir as tuas marcações.', intro: 'Vê as tuas marcações, protege o teu tempo e mantém o dia organizado sem folhas soltas.', points: [],
      sections: [
        { title: 'Vê o teu dia como preferires', text: 'Alterna entre a vista diária, semanal e mensal e volta a hoje num clique.' },
        { title: 'Estados que se entendem de relance', text: 'As cores mostram o que está pendente, confirmado, em risco, concluído, cancelado ou foi falta.' },
        { title: 'Altera no próprio calendário', text: 'Arrasta uma marcação para mudar a hora ou o dia e ajusta a duração diretamente na agenda.' },
        { title: 'Marcações que se repetem', text: 'Cria recorrências semanais, quinzenais ou mensais. Depois, altera apenas uma sessão ou todas as seguintes.' },
        { title: 'Conflitos antes de acontecerem', text: 'Recebe um aviso quando uma marcação colide com outra, uma sessão de grupo ou o intervalo após o serviço.' },
        { title: 'Reserva tempo para ti', text: 'Define pausas regulares, como almoço, e protege o teu horário de trabalho.' },
        { title: 'Férias, feriados e dias de folga', text: 'Bloqueia um compromisso pessoal, um dia encerrado ou vários dias de férias na agenda.' },
        { title: 'Uma marcação com contexto', text: 'Guarda notas internas, escolhe o serviço e acompanha o cliente em cada sessão.' },
        { title: 'Pacotes e vouchers na marcação', text: 'Aplica pacotes ou vouchers e acompanha automaticamente as sessões que ainda estão disponíveis.' },
        { title: 'Cria marcações rapidamente', text: 'Clica num horário livre para marcar e cria um novo cliente no mesmo momento, se for preciso.' },
        { title: 'Acompanha até ao fim', text: 'Reagenda, confirma, cancela, reativa, conclui, regista uma falta ou assinala o pagamento.' },
        { title: 'Sessões de grupo', text: 'Também podes gerir sessões de grupo, participantes e presenças no plano Pro.' },
      ],
    },
    {
      slug: 'lembretes', label: 'Lembretes', detail: 'Comunica no momento certo', eyebrow: 'Lembretes', title: 'Lembra sem escrever a mesma mensagem todos os dias.', intro: 'Prepara comunicações para os teus clientes e envia-as no momento certo, por WhatsApp ou SMS. O envio fica sempre sob o teu controlo.', points: [],
      sections: [
        { title: 'Modelos de mensagem à tua maneira', text: 'Personaliza textos para confirmação, reagendamento, aniversário, pagamentos, recibos, reativação e cancelamentos.' },
        { title: 'Dados preenchidos automaticamente', text: 'O nome do cliente, serviço, data, hora, valor e identificação do negócio entram no texto automaticamente.' },
        { title: 'Pré-visualização antes de enviar', text: 'Vê como a mensagem fica antes de a usar.' },
        { title: 'Confirmação logo após marcar', text: 'Ao criar ou reagendar uma marcação, o Auxio pergunta se queres enviar a confirmação ao cliente.' },
        { title: 'Lembretes de marcações por confirmar', text: 'Vê rapidamente quais os clientes que ainda não confirmaram uma sessão e prepara a mensagem certa.' },
        { title: 'Envio pelo teu WhatsApp ou SMS', text: 'O Auxio abre a mensagem já preenchida; tu revês e decides quando enviar.' },
        { title: 'Aniversários dos clientes', text: 'Recebe um aviso e prepara uma mensagem personalizada para celebrar a data.' },
        { title: 'Pagamentos em atraso', text: 'Cria lembretes com o valor em falta e os dias de atraso.' },
        { title: 'Convites para voltar', text: 'Reaproxima clientes que já não marcam há algum tempo com uma mensagem preparada a partir da última sessão.' },
        { title: 'Cancelamentos com contexto', text: 'Comunica um cancelamento com o motivo, data e hora da marcação já incluídos.' },
        { title: 'Recibos por email', text: 'Envia recibos ao cliente com uma mensagem personalizada e os documentos anexados.' },
        { title: 'Alertas no dispositivo', text: 'Recebe notificações no teu dispositivo sobre novas marcações e mensagens, mesmo com o Auxio fechado.' },
        { title: 'Define a antecedência', text: 'Escolhe ser avisada 1 ou 3 dias antes de uma marcação que ainda não foi confirmada.' },
        { title: 'Alertas de pagamento e objetivo', text: 'Define quando queres ser avisada de pagamentos em atraso e acompanha os marcos do objetivo anual.' },
        { title: 'Horário silencioso', text: 'Define um período em que não queres receber notificações no dispositivo.' },
      ],
    },
    {
      slug: 'fichas-clientes', label: 'Fichas de clientes', detail: 'Toda a informação reunida', eyebrow: 'Clientes', title: 'A informação certa, quando precisas dela.', intro: 'Centraliza os dados, notas e histórico de cada cliente numa ficha simples de consultar.', points: [],
      sections: [
        { title: 'Dados pessoais e contactos', text: 'Guarda nome, data de nascimento, telefone, email e morada numa só ficha.' },
        { title: 'Dados para faturação', text: 'Regista NIF e morada completa, com validação do formato dos campos.' },
        { title: 'Preferências de cada cliente', text: 'Anota os dias e horários preferidos e define o intervalo recomendado entre sessões.' },
        { title: 'Notas e ficheiros', text: 'Guarda notas na ficha e nas marcações, com documentos anexados de forma privada.' },
        { title: 'Etiquetas à tua maneira', text: 'Cria etiquetas com cor, como VIP, Alergia, Pós-cirúrgico ou Seguro de saúde.' },
        { title: 'Histórico de marcações', text: 'Consulta serviços, datas, estados, pagamentos e notas. Podes reagendar diretamente a partir da ficha.' },
        { title: 'Histórico comercial', text: 'Vê pacotes, vouchers, recibos e o valor total gerado por cada cliente.' },
        { title: 'Pagamentos e recibos', text: 'Acompanha valores recebidos, pendentes ou em atraso, incluindo cobranças de sessões de grupo.' },
        { title: 'Pesquisa rápida e filtros', text: 'Pesquisa por nome, telemóvel ou email, filtra por etiquetas e organiza por receita ou última visita.' },
        { title: 'Clientes a reativar', text: 'Identifica quem já não marca há algum tempo e volta a entrar em contacto no momento certo.' },
        { title: 'Exportação dos teus dados', text: 'Exporta os dados do negócio, incluindo clientes, marcações, notas e informação financeira.' },
      ],
      notice: {
        title: 'Privacidade dos seus clientes',
        text: 'Os dados dos seus clientes permanecem associados exclusivamente ao seu negócio. O Auxio não utiliza essa informação para contactar os seus clientes, promover serviços de terceiros ou beneficiar negócios concorrentes.',
      },
    },
    {
      slug: 'servicos-pacotes', label: 'Serviços, pacotes e vouchers', detail: 'Define e acompanha o que vendes', eyebrow: 'Serviços', title: 'Define uma vez. Usa em cada marcação.', intro: 'Organiza os teus serviços, pacotes de sessões e vouchers para que o acompanhamento seja mais simples.', points: [],
      sections: [
        { title: 'Catálogo de serviços organizado', text: 'Cria todos os serviços que prestas e mantém-nos reunidos num só lugar.' },
        { title: 'Informação essencial em cada serviço', text: 'Define nome, descrição, preço, duração e intervalo necessário após cada sessão.' },
        { title: 'Preço, IVA e comissões', text: 'Configura o escalão de IVA de cada serviço e, quando aplicável, a comissão do espaço.' },
        { title: 'Categorias com cor', text: 'Organiza os serviços por categorias personalizadas, com cores, pesquisa e filtros.' },
        { title: 'Serviços ativos quando precisas', text: 'Desativa serviços temporariamente sem perder o histórico de marcações e vendas anteriores.' },
        { title: 'Serviços de grupo', text: 'Configura lotação, cor, taxa de inscrição, seguro e mensalidade para sessões de grupo no plano Pro.' },
        { title: 'Vê o que é mais procurado', text: 'Identifica o serviço com mais marcações no mês e compara a atividade com o mês anterior.' },
        { title: 'Cria pacotes à tua medida', text: 'Junta um ou vários serviços num pacote, define o número de sessões e o preço total.' },
        { title: 'Preço por sessão calculado automaticamente', text: 'Vê o valor médio de cada sessão dentro do pacote, sem fazer contas manualmente.' },
        { title: 'Vende pacotes na ficha do cliente', text: 'Associa um pacote a um cliente e acompanha as sessões usadas e restantes.' },
        { title: 'Pagamento total ou em prestações', text: 'Regista a venda de um pacote paga de uma vez ou dividida em prestações.' },
      { title: 'Pacotes ligados à agenda', text: 'Ao marcar, o pacote é aplicado e a agenda mostra o número da sessão, por exemplo, 2/6. Ao cancelar ou arrastar para outro dia, a numeração é recalculada automaticamente.' },
        { title: 'Vouchers para oferecer ou utilizar mais tarde', text: 'Vende vouchers associados a um serviço, com código e data de validade.' },
        { title: 'Vouchers aplicados na marcação', text: 'Usa o voucher diretamente ao criar uma marcação; fica registado como sessão já paga.' },
        { title: 'Tudo ligado às fichas e à faturação', text: 'Serviços, pacotes e vouchers ficam associados ao cliente, às marcações e aos valores do negócio.' },
      ],
    },
    {
      slug: 'sessoes-grupo', label: 'Sessões de grupo', detail: 'Gere turmas com facilidade', eyebrow: 'Sessões de grupo', title: 'Gere uma sessão de grupo sem perder ninguém pelo caminho.', intro: 'Mantém participantes, horários e presenças reunidos para acompanhar cada turma com clareza. Disponível no plano Pro.', points: [],
      sections: [
        { title: 'Cria sessões de grupo', text: 'Define o tipo de sessão, data, hora, duração, cor e lotação.' },
        { title: 'Sessões únicas ou recorrentes', text: 'Cria uma aula isolada ou uma série semanal, quinzenal ou em dias específicos da semana.' },
        { title: 'Lotação sempre visível', text: 'Vê se a sessão está vazia, tem vagas ou está lotada, incluindo o número de inscritos.' },
        { title: 'Inscreve participantes', text: 'Adiciona um cliente a uma sessão isolada, por exemplo para uma aula experimental, ou à série completa.' },
        { title: 'Turmas regulares', text: 'Quem é inscrito numa série passa automaticamente a constar nas sessões futuras dessa turma.' },
        { title: 'Controlo de presenças', text: 'Regista quem esteve presente, faltou ou ainda não tem presença assinalada.' },
        { title: 'Gestão de inscrições', text: 'Remove alguém apenas de uma sessão ou das sessões futuras, preservando o histórico já ocorrido.' },
        { title: 'Mensalidades por aluno', text: 'Define uma mensalidade por participante, incluindo valores diferentes quando necessário.' },
        { title: 'Taxas e seguros', text: 'Regista taxas de inscrição, seguros e mensalidades, com o estado de pagamento acompanhado na ficha do cliente.' },
        { title: 'Edita ou termina uma série', text: 'Altera uma sessão isolada ou todas as futuras e termina uma turma a partir de uma data escolhida.' },
        { title: 'Cancelamentos e reposições', text: 'Cancela com motivo, mantém o registo na agenda e cria uma reposição que conserva os participantes.' },
        { title: 'Tudo integrado na agenda', text: 'As sessões ocupam espaço na agenda, aparecem com a sua cor e entram na gestão diária do teu horário.' },
      ],
    },
    {
      slug: 'faturacao-recibos', label: 'Faturação e recibos', detail: 'Acompanha pagamentos', eyebrow: 'Faturação', title: 'Sabe o que entrou, o que falta receber e o que saiu.', intro: 'Acompanha receitas, despesas, pagamentos e documentos dos teus clientes para manteres as finanças do negócio organizadas.', points: [],
      sections: [
        { title: 'Resumo do mês', text: 'Vê de imediato quanto faturaste, o lucro obtido e as despesas do mês selecionado.' },
        { title: 'Evolução ao longo do ano', text: 'Acompanha a evolução mensal da receita e do lucro para perceberes o ritmo do negócio.' },
        { title: 'Objetivo anual', text: 'Define o teu objetivo de faturação e acompanha o valor acumulado e o que falta atingir.' },
        { title: 'Faturação por serviço', text: 'Descobre quais os serviços que mais contribuem para a receita em cada mês.' },
        { title: 'Despesas sob controlo', text: 'Regista despesas pontuais ou recorrentes e mantém o total mensal sempre atualizado.' },
        { title: 'Comissão do espaço', text: 'Se trabalhas à percentagem, acompanha a comissão a pagar pelo espaço sem fazer contas à parte.' },
        { title: 'Contas a receber', text: 'Consulta os valores pendentes por cliente e sabe rapidamente quem tem pagamentos em atraso.' },
        { title: 'Confirma pagamentos', text: 'Marca pagamentos como recebidos na faturação ou diretamente a partir da agenda.' },
        { title: 'Lembretes de pagamento', text: 'Prepara lembretes por WhatsApp com o valor em falta e os dias de atraso.' },
        { title: 'Histórico de pagamentos', text: 'Pesquisa e filtra os pagamentos por cliente, serviço ou período: mês, trimestre, ano ou tudo.' },
        { title: 'Pacotes a prestações', text: 'Acompanha o que já foi pago e o que falta receber em cada pacote vendido a prestações.' },
        { title: 'Pacotes e vouchers na receita', text: 'As vendas de pacotes e vouchers entram automaticamente no acompanhamento financeiro.' },
        { title: 'Documentos dos teus clientes', text: 'Guarda recibos, faturas e faturas-recibo emitidos no Portal das Finanças na ficha de cada cliente.' },
        { title: 'Documentos ligados à marcação', text: 'Associa cada documento à marcação correspondente para manteres o histórico completo.' },
        { title: 'Partilha e descarrega', text: 'Envia documentos ao cliente ou descarrega um ou vários ficheiros quando precisares.' },
        { title: 'Mapa de recibos', text: 'Exporta o mapa de recibos em CSV ou PDF e envia os documentos selecionados ao contabilista.' },
      ],
    },
    {
      slug: 'visao-negocio', label: 'Visão do negócio', detail: 'Percebe o que merece atenção', eyebrow: 'Visão do negócio', title: 'Começa o dia a saber o que merece atenção.', intro: 'Vê os indicadores mais importantes do teu trabalho num só lugar e toma decisões com mais contexto.', points: [],
      sections: [
        { title: 'O teu dia num relance', text: 'Vê as marcações de hoje, o que ainda falta fazer e a próxima sessão em destaque.' },
        { title: 'A próxima sessão com contexto', text: 'Consulta cliente, serviço, duração, estado, notas e contacto sem sair do início.' },
        { title: 'Confirmações que precisam de atenção', text: 'Identifica marcações ainda sem confirmação e confirma-as diretamente.' },
        { title: 'Marcações fora do horário', text: 'Recebe um aviso quando uma marcação entra em conflito com férias, feriados, dias encerrados ou compromissos pessoais.' },
        { title: 'Horários livres para encaixes', text: 'Encontra o próximo bloco disponível e vê espaços livres para amanhã, respeitando horários, pausas e sessões de grupo.' },
        { title: 'Amanhã preparado hoje', text: 'Consulta antecipadamente as marcações do dia seguinte, com os respetivos estados e horários livres.' },
        { title: 'Lembretes por enviar', text: 'Vê quem ainda precisa de confirmação e abre a mensagem por WhatsApp ou SMS.' },
        { title: 'Pagamentos pendentes', text: 'Acompanha valores por receber, marca pagamentos como recebidos e envia lembretes de pagamento.' },
        { title: 'Resultados da semana', text: 'Vê a receita semanal, a comparação com a semana anterior, sessões realizadas e faltas.' },
        { title: 'Serviços que mais contribuem', text: 'Percebe quais os serviços que mais contribuíram para a receita da semana.' },
        { title: 'Clientes a reativar', text: 'Identifica clientes sem sessão há algum tempo e abre um convite de regresso por WhatsApp.' },
        { title: 'Vouchers por utilizar', text: 'Consulta vouchers ativos, a respetiva validade e inicia uma marcação diretamente a partir deles.' },
      ],
    },
  ],
  en: [
    {
      slug: 'agenda-horarios', label: 'Calendar and hours', detail: 'Organise your day', eyebrow: 'Calendar', title: 'Everything you need to manage your appointments.', intro: 'See your appointments, protect your time and keep your day organised without loose notes.', points: [],
      sections: [
        { title: 'See your day your way', text: 'Switch between daily, weekly and monthly views, and return to today in one click.' },
        { title: 'Statuses at a glance', text: 'Colours show what is pending, confirmed, at risk, completed, cancelled or a no-show.' },
        { title: 'Update in the calendar', text: 'Drag an appointment to change its time or day, and adjust its duration directly in the calendar.' },
        { title: 'Recurring appointments', text: 'Create weekly, fortnightly or monthly recurrences. Then change just one session or every following one.' },
        { title: 'Conflicts before they happen', text: 'Get an alert when an appointment clashes with another, a group session or the buffer after a service.' },
        { title: 'Make time for yourself', text: 'Set regular breaks, such as lunch, and protect your working hours.' },
        { title: 'Holidays and days off', text: 'Block a personal commitment, a closed day or several days of holiday in the calendar.' },
        { title: 'An appointment with context', text: 'Keep internal notes, choose the service and follow each client in every session.' },
        { title: 'Packages and vouchers in the appointment', text: 'Apply packages or vouchers and automatically track the sessions still available.' },
        { title: 'Create appointments quickly', text: 'Click a free time slot to book and create a new client at the same time if needed.' },
        { title: 'Follow it through', text: 'Reschedule, confirm, cancel, reactivate, complete, mark a no-show or record payment.' },
        { title: 'Group sessions', text: 'You can also manage group sessions, participants and attendance on the Pro plan.' },
      ],
    },
    {
      slug: 'lembretes', label: 'Reminders', detail: 'Communicate at the right time', eyebrow: 'Reminders', title: 'Send reminders without writing the same message every day.', intro: 'Prepare client communications and send them at the right time through WhatsApp or SMS. You always stay in control of sending.', points: [],
      sections: [
        { title: 'Message templates your way', text: 'Personalise text for confirmations, rescheduling, birthdays, payments, receipts, reactivation and cancellations.' },
        { title: 'Details filled in automatically', text: 'The client name, service, date, time, amount and business identity are inserted into the message automatically.' },
        { title: 'Preview before sending', text: 'See how the message looks before you use it.' },
        { title: 'Confirmation as soon as you book', text: 'When you create or reschedule an appointment, Auxio asks whether you want to send a confirmation to the client.' },
        { title: 'Reminders for unconfirmed appointments', text: 'Quickly see which clients have not yet confirmed and prepare the right message.' },
        { title: 'Send through WhatsApp or SMS', text: 'Auxio opens a pre-filled message; you review it and decide when to send it.' },
        { title: 'Client birthdays', text: 'Get an alert and prepare a personal message to celebrate the date.' },
        { title: 'Overdue payments', text: 'Create reminders with the amount due and the number of days overdue.' },
        { title: 'Invitations to return', text: 'Reconnect with clients who have not booked for some time using a message based on their last session.' },
        { title: 'Cancellations with context', text: 'Communicate a cancellation with the reason, date and time already included.' },
        { title: 'Receipts by email', text: 'Send receipts with a personalised message and the documents attached.' },
        { title: 'Device alerts', text: 'Receive notifications on your device about new appointments and messages, even when Auxio is closed.' },
        { title: 'Choose how far in advance', text: 'Choose to be alerted one or three days before an appointment that is still unconfirmed.' },
        { title: 'Payment and goal alerts', text: 'Choose when to be alerted about overdue payments and track annual-goal milestones.' },
        { title: 'Quiet hours', text: 'Set a period when you do not want to receive device notifications.' },
      ],
    },
    {
      slug: 'fichas-clientes', label: 'Client records', detail: 'All information together', eyebrow: 'Clients', title: 'The right information when you need it.', intro: 'Keep each client’s details, notes and history in one simple record.', points: [],
      sections: [
        { title: 'Personal details and contacts', text: 'Keep names, dates of birth, phone numbers, emails and addresses in one record.' },
        { title: 'Billing details', text: 'Store tax numbers and full addresses, with field format validation.' },
        { title: 'Each client’s preferences', text: 'Note preferred days and times, and define the recommended interval between sessions.' },
        { title: 'Notes and files', text: 'Keep notes in the client record and appointments, with private document attachments.' },
        { title: 'Labels your way', text: 'Create colour-coded labels such as VIP, Allergy, Post-surgery or Health insurance.' },
        { title: 'Appointment history', text: 'Review services, dates, statuses, payments and notes. You can reschedule directly from the record.' },
        { title: 'Sales history', text: 'See packages, vouchers, receipts and the total value generated by each client.' },
        { title: 'Payments and receipts', text: 'Track received, pending or overdue amounts, including group-session charges.' },
        { title: 'Quick search and filters', text: 'Search by name, phone number or email, filter by labels and sort by revenue or last visit.' },
        { title: 'Clients to reactivate', text: 'Identify people who have not booked for some time and reach out at the right moment.' },
        { title: 'Export your data', text: 'Export business data, including clients, appointments, notes and financial information.' },
      ],
      notice: {
        title: 'Your clients’ privacy',
        text: 'Your clients’ data remains associated exclusively with your business. Auxio does not use that information to contact your clients, promote third-party services or benefit competing businesses.',
      },
    },
    {
      slug: 'servicos-pacotes', label: 'Services, packages and vouchers', detail: 'Define and track what you sell', eyebrow: 'Services', title: 'Set it up once. Use it in every appointment.', intro: 'Organise services, session packages and vouchers so they are easier to manage.', points: [],
      sections: [
        { title: 'An organised service catalogue', text: 'Create every service you offer and keep them together in one place.' },
        { title: 'Key information for every service', text: 'Define a name, description, price, duration and the time needed after each session.' },
        { title: 'Price, VAT and commissions', text: 'Set the VAT band for each service and, where applicable, the venue commission.' },
        { title: 'Colour-coded categories', text: 'Organise services into custom categories, with colours, search and filters.' },
        { title: 'Services active when you need them', text: 'Temporarily deactivate services without losing past appointment and sales history.' },
        { title: 'Group services', text: 'Set capacity, colour, enrolment fee, insurance and monthly fees for group sessions on the Pro plan.' },
        { title: 'See what is most popular', text: 'Identify the service with the most appointments this month and compare activity with last month.' },
        { title: 'Create packages your way', text: 'Combine one or several services in a package, define the number of sessions and total price.' },
        { title: 'Price per session calculated automatically', text: 'See the average value of every session in a package without doing the maths.' },
        { title: 'Sell packages in the client record', text: 'Associate a package with a client and track used and remaining sessions.' },
        { title: 'Pay in full or in instalments', text: 'Record a package sale paid at once or divided into instalments.' },
      { title: 'Packages connected to the calendar', text: 'When you book, the package is applied and the calendar shows the session number, for example 2/6. If you cancel or drag it to another day, the numbering is recalculated automatically.' },
        { title: 'Vouchers to give or use later', text: 'Sell vouchers linked to a service, with a code and expiry date.' },
        { title: 'Vouchers applied to an appointment', text: 'Use a voucher directly when creating an appointment; it is recorded as an already-paid session.' },
        { title: 'Connected to client records and billing', text: 'Services, packages and vouchers stay linked to the client, appointments and business figures.' },
      ],
    },
    {
      slug: 'sessoes-grupo', label: 'Group sessions', detail: 'Manage groups with ease', eyebrow: 'Group sessions', title: 'Manage a group session without losing track of anyone.', intro: 'Keep participants, schedules and attendance together to follow every group clearly. Available on the Pro plan.', points: [],
      sections: [
        { title: 'Create group sessions', text: 'Define the session type, date, time, duration, colour and capacity.' },
        { title: 'One-off or recurring sessions', text: 'Create a single class or a weekly, fortnightly or selected-days series.' },
        { title: 'Capacity always visible', text: 'See whether a session is empty, has places or is full, including the number of participants.' },
        { title: 'Enrol participants', text: 'Add a client to one session, for example for a trial class, or to the full series.' },
        { title: 'Regular groups', text: 'Anyone enrolled in a series is automatically added to that group’s future sessions.' },
        { title: 'Attendance tracking', text: 'Record who attended, was absent or does not yet have an attendance record.' },
        { title: 'Manage enrolments', text: 'Remove someone from just one session or future sessions while keeping past history.' },
        { title: 'Monthly fees per participant', text: 'Set a monthly fee per participant, including different values when needed.' },
        { title: 'Fees and insurance', text: 'Record enrolment fees, insurance and monthly fees, with payment status in the client record.' },
        { title: 'Edit or end a series', text: 'Update one session or all future ones, and end a group from a chosen date.' },
        { title: 'Cancellations and make-up sessions', text: 'Cancel with a reason, keep the record in the calendar and create a make-up session with the same participants.' },
        { title: 'Integrated with your calendar', text: 'Sessions take up calendar space, show their colour and are part of your daily schedule.' },
      ],
    },
    {
      slug: 'faturacao-recibos', label: 'Billing and receipts', detail: 'Track payments', eyebrow: 'Billing', title: 'Know what came in, what is still due and what went out.', intro: 'Track income, expenses, payments and client documents to keep your business finances organised.', points: [],
      sections: [
        { title: 'Monthly overview', text: 'See at a glance how much you billed, the profit made and your expenses for the selected month.' },
        { title: 'Progress over the year', text: 'Track monthly income and profit to understand your business rhythm.' },
        { title: 'Annual goal', text: 'Set a billing goal and follow the amount accumulated and what remains to reach it.' },
        { title: 'Billing by service', text: 'Find out which services contribute the most revenue each month.' },
        { title: 'Expenses under control', text: 'Record one-off or recurring expenses and keep the monthly total up to date.' },
        { title: 'Venue commission', text: 'If you work on commission, track the amount owed to the venue without separate calculations.' },
        { title: 'Accounts receivable', text: 'Check pending amounts by client and quickly see who has overdue payments.' },
        { title: 'Confirm payments', text: 'Mark payments as received in billing or directly from the calendar.' },
        { title: 'Payment reminders', text: 'Prepare WhatsApp reminders with the amount due and the number of days overdue.' },
        { title: 'Payment history', text: 'Search and filter payments by client, service or period: month, quarter, year or all time.' },
        { title: 'Packages by instalment', text: 'Track what has been paid and what remains due for each package sold in instalments.' },
        { title: 'Packages and vouchers in revenue', text: 'Package and voucher sales are automatically included in your financial overview.' },
        { title: 'Your client documents', text: 'Keep receipts, invoices and invoice-receipts issued through the tax portal in every client record.' },
        { title: 'Documents linked to appointments', text: 'Associate each document with its appointment to keep the full history together.' },
        { title: 'Share and download', text: 'Send documents to the client or download one or several files whenever you need to.' },
        { title: 'Receipt statement', text: 'Export the receipt statement in CSV or PDF and send selected documents to your accountant.' },
      ],
    },
    {
      slug: 'visao-negocio', label: 'Business overview', detail: 'See what needs attention', eyebrow: 'Business overview', title: 'Start the day knowing what needs your attention.', intro: 'See the key indicators for your work in one place and make decisions with more context.', points: [],
      sections: [
        { title: 'Your day at a glance', text: 'See today’s appointments, what is still to do and your next session in focus.' },
        { title: 'Your next session with context', text: 'See the client, service, duration, status, notes and contact details without leaving home.' },
        { title: 'Confirmations that need attention', text: 'Identify appointments that still need confirmation and confirm them directly.' },
        { title: 'Appointments outside your hours', text: 'Get an alert when an appointment conflicts with holidays, closed days or personal commitments.' },
        { title: 'Free times for last-minute bookings', text: 'Find the next available slot and see free time tomorrow, respecting working hours, breaks and group sessions.' },
        { title: 'Prepare tomorrow today', text: 'Review the next day’s appointments in advance, with their statuses and free slots.' },
        { title: 'Reminders to send', text: 'See who still needs confirmation and open the message in WhatsApp or SMS.' },
        { title: 'Pending payments', text: 'Track amounts due, mark payments as received and send payment reminders.' },
        { title: 'This week’s results', text: 'See weekly revenue, comparison with the previous week, completed sessions and no-shows.' },
        { title: 'Your top contributing services', text: 'Understand which services contributed most to this week’s revenue.' },
        { title: 'Clients to reactivate', text: 'Identify clients without a recent session and open a WhatsApp invitation to return.' },
        { title: 'Vouchers to use', text: 'See active vouchers, their expiry dates and start an appointment directly from them.' },
      ],
    },
  ],
};
